on:
  push:
    branches:
      - master

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          release-type: node
          package-name: standard-version
          changelog-types: '[
            {
              "type": "feat",
              "section": "ğŸŒŸ Features",
              "hidden": false
            },
            {
              "type": "fix",
              "section": "ğŸ Bug Fixes",
              "hidden": false
            },
            {
              "type": "docs",
              "section": "ğŸ“– Docs",
              "hidden": false
            },
            {
              "type": "style",
              "section": "ğŸ¨ Styling",
              "hidden": false
            },
            {
              "type": "refactor",
              "section": "ğŸ­ Code Refactoring",
              "hidden": false
            },
            {
              "type": "perf",
              "section": "ğŸ›  Performance Improvements",
              "hidden": false
            },
            {
              "type": "test",
              "section": "ğŸš§ Tests",
              "hidden": false
            },
            {
              "type": "build",
              "section": "ğŸ“¦ Build System",
              "hidden": false
            },
            {
              "type": "revert",
              "section": "ğŸŒ€ Reverts",
              "hidden": false
            },
            {
              "type": "ci",
              "section": "ğŸ¯ CI",
              "hidden": false
            },
            {
              "type": "ui",
              "section": "ğŸ’„ Improvement UI",
              "hidden": false
            },
            {
              "type": "chore",
              "section": "ğŸš¦ Chore",
              "hidden": false
            }
          ]'

      # â†“â†“ The logic below handles deploy to gh â†“â†“

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v1
        with:
          node-version: 16
        if: ${{ steps.release.outputs.release_created }}

      - run: npm install
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: Update PicX
        if: ${{ steps.release.outputs.release_created }}
